<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
    <SelfContained>true</SelfContained>
    <BaseOutputPath>bin\PackageDesigner\</BaseOutputPath>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Tests/**/*.cs" />
    <None Remove="Tests/**" />
    <Content Remove="Tests/**" />
    <EmbeddedResource Remove="Tests/**" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="Resources\manifest-schema.json" />
    <EmbeddedResource Include="Resources\manifest-schema.json" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="NJsonSchema" Version="11.0.0" />
  </ItemGroup>
</Project>