namespace PackageDesigner.Models;

/// <summary>
/// In-memory model for the editor's PackageProject. NOTE: this is NOT the
/// shipped manifest.json (which lives inside the published package and is
/// regenerated by MetricGenerator on each save, then validated by
/// ManifestValidator against Resources/manifest-schema.json). Per-metric
/// override values live in MetricOverrides (editor-side only).
/// </summary>
public class PackageManifest
{
    public string Name { get; set; } = "";
    public string Version { get; set; } = "";
    public string Type { get; set; } = "gauge";
    public string? Description { get; set; }
    public AgentConfig Agent { get; set; } = new();
    public DatabaseConfig? Database { get; set; }

    /// <summary>
    /// Per-metric override values (Label/Unit/Warn/Crit). Editor-side only;
    /// never serialized into the shipped manifest.json (which is regenerated
    /// by <c>MetricGenerator</c> on each save and validated by
    /// <c>ManifestValidator</c>). Nullable so existing .pkgproj files
    /// deserialize cleanly — null/absent means "no overrides".
    /// </summary>
    public Dictionary<string, MetricOverride>? MetricOverrides { get; set; }
}
